# Generated by Django 2.2 on 2019-05-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('excerpt', models.TextField()),
                ('tag', models.TextField()),
                ('category', models.TextField()),
                ('author', models.TextField()),
            ],
        ),
    ]
