# Generated by Django 2.2 on 2019-05-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectCard',
            new_name='Projects',
        ),
    ]
