# Generated by Django 2.2 on 2019-05-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_auto_20190521_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
