# Generated by Django 2.2 on 2019-06-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0005_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approval_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
